#!/bin/bash
# This hook is run after a new project is activated.

VENV_FILE_EXTENSION=.venv
REQUIREMENTS_FILE=requirements-dev-tools.txt
VENV_FILE_EXTENSION=.venv
REQUIREMENTS_SOURCE=$WORKON_HOME/virtualenvwrapper-customizations
IPYKERNEL_REGISTER_SCRIPT=ipykernel_register.sh

if [[ -n $VIRTUAL_ENV && ! -f "./$VENV_FILE_EXTENSION" ]]; then
    echo $(basename $VIRTUAL_ENV) > ./$VENV_FILE_EXTENSION
fi

if [[ ! -f "./$REQUIREMENTS_FILE" ]]; then
    if [ -f "$REQUIREMENTS_SOURCE/$REQUIREMENTS_FILE" ]; then
			cp $REQUIREMENTS_SOURCE/$REQUIREMENTS_FILE ./
		else
			touch ./$REQUIREMENTS_FILE
    fi
fi

pip install -r ./$REQUIREMENTS_FILE

if [[ -n $VIRTUAL_ENV && -f "$REQUIREMENTS_SOURCE/settings.json" ]]; then
    mkdir .vscode
    cat $REQUIREMENTS_SOURCE/settings.json | jq --arg venv "$VIRTUAL_ENV/bin/python" '.["python.pythonPath"] |= $venv' > .vscode/settings.json
fi

if [[ -n $VIRTUAL_ENV && -f "$REQUIREMENTS_SOURCE/launch.json" && -n .vscode ]]; then
    cp $REQUIREMENTS_SOURCE/launch.json .vscode/launch.json
fi

if [[ -n $VIRTUAL_ENV && -f "$REQUIREMENTS_SOURCE/.bandit" ]]; then
    cp $REQUIREMENTS_SOURCE/.bandit ./
fi

if [[ -n $VIRTUAL_ENV && -f "$REQUIREMENTS_SOURCE/.flake8" ]]; then
    cp $REQUIREMENTS_SOURCE/.flake8 ./
fi

if [[ -n $VIRTUAL_ENV && -f "$REQUIREMENTS_SOURCE/.pydocstyle" ]]; then
    cp $REQUIREMENTS_SOURCE/.pydocstyle ./
fi

if [[ -n $VIRTUAL_ENV && -f "$REQUIREMENTS_SOURCE/.pylintrc" ]]; then
    cp $REQUIREMENTS_SOURCE/.pylintrc ./
fi

if [[ -n $VIRTUAL_ENV && -f "$REQUIREMENTS_SOURCE/$IPYKERNEL_REGISTER_SCRIPT" ]]; then
    cp $REQUIREMENTS_SOURCE/$IPYKERNEL_REGISTER_SCRIPT ./
fi

