#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

REQUIREMENTS_FILE=requirements-dev-tools.txt
VENV_FILE_EXTENSION=.venv
REQUIREMENTS_SOURCE=$WORKON_HOME/virtualenvwrapper-customizations
PROJECT_LINK=$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME

if [[ -f "$PROJECT_LINK" ]]; then
	PROJECT_FOLDER=$(cat $PROJECT_LINK)

	VENV_FILE_LOCATION=$PROJECT_FOLDER/$VENV_FILE_EXTENSION
	echo $(basename $VIRTUAL_ENV) > $VENV_FILE_LOCATION

	if [[ -n $PROJECT_FOLDER && ! -f "$PROJECT_FOLDER/$REQUIREMENTS_FILE" ]]; then
		if [ -f "$REQUIREMENTS_SOURCE/$REQUIREMENTS_FILE" ]; then
			cp $REQUIREMENTS_SOURCE/$REQUIREMENTS_FILE $PROJECT_FOLDER/
		else
			touch $PROJECT_FOLDER/$REQUIREMENTS_FILE
		fi
	fi

	pip install -r $PROJECT_FOLDER/$REQUIREMENTS_FILE

	if [[ -n $PROJECT_FOLDER && -f "$REQUIREMENTS_SOURCE/settings.json" ]]; then
		mkdir $PROJECT_FOLDER/.vscode
		cat $REQUIREMENTS_SOURCE/settings.json | jq --arg venv "$VIRTUAL_ENV/bin/python" '.["python.pythonPath"] |= $venv' > $PROJECT_FOLDER/.vscode/settings.json
	fi

	if [[ -f "$REQUIREMENTS_SOURCE/launch.json" && -n $PROJECT_FOLDER/.vscode ]]; then
		cp $REQUIREMENTS_SOURCE/launch.json $PROJECT_FOLDER/.vscode/launch.json
	fi
fi

